gamepad_driver = all
locale = fr
csrf_allowed_origins = https://CHANGEME_ip_du_navigateur:47990
nvenc_preset = 1
nvenc_twopass = disabled
nvenc_vbv_increase = 100
nvenc_spatial_aq = enabled
output_name = CHANGEME_guid_de_l_ecran_virtuel
dd_configuration_option = ensure_only_display
dd_resolution_option = auto
dd_refresh_rate_option = auto
system_tray = disabled
